### PR TITLE
Fix inconsistency after InstallSnapshot

### LINKED ISSUE #127: InstallSnapshot can cause inconsistency (Entity grasp is insufficient)
## Expected Behavior

The member that received `InstallSnapshot` copies all snapshots of the sender-saved ones.

## Current Behavior

Snapshot synchronization copies snapshots by *only* journal of compaction that `InstallSnapshot` sender executed.
Snapshots will be also updated by snapshot synchronization.

## Steps to Reproduce

1. The follower-member *A* synchronizes snapshots from the leader-member  *B* by receiving `InstallSnapshot` from the leader-member
2. The follower-member saves a snapshot of unknown entity *C* in this process
3. Member *A* promotes to a leader for any reason
4. A follower-member becomes a "delayed follower" for node failure or network failure
5. Member *A* sends `InstallSnapshot` to the delayed follower before entity *C* updated in member *A*
6. The delayed follower can't copy the entity *C*'s snapshot since member *A* has not saved the snapshot in any compactions

**Example:**

(This scenario will be reproduced in an integration test case)

image

### PR DESCRIPTION
**Pull request by negokaz**
Closes #127 

## Overview

- Introduce new event `SnapshotCopied` that `SnapshotSyncManager` saves after copying snapshots
    - This event contains `entityId`s that indicate that the snapshot that was copied
    - Tags this event with `EntitySnapshotsUpdatedTag`(`CompactionCompletedTag`)
    - This tagging allows that follower's `SnapshotSyncManager` reads `SnapshotCopied`s that the leader's `SnapshotSyncManager` persisted
    - Follower members can know updated snapshots with `SnapshotCopied` that produced by snapshot synchronization that the leader has executed
- `SnapshotSyncManager` reads `CompactionCompleted` and also `SnapshotCopied`
    - `SnapshotSyncManager` can identify all `entityId`s that should copy snapshots

## NOTE

This change does not fix the potential consistency problem.
Systems that already have executed `InstallSnapshot` may still occur this issue even if applying this change.

### CODE REVIEW

File: src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala [hunk 1]
```diff
@@ -28,4 +42,66 @@ final class RaftEventJournalTestKit(system: ActorSystem, settings: ClusterReplic
...
+
+  private def setNextSeqNo(envelope: EventEnvelope): Unit =
+    nextSeqNoByPersistenceId = nextSeqNoByPersistenceId.updated(envelope.persistenceId, envelope.sequenceNr + 1)
+
+  implicit val materializer: Materializer = Materializer(system)
+
+  /**
+    * Receive for max time next n events that have been persisted in the journal.
+    */
+  def receivePersisted[T](persistenceId: String, n: Int)(implicit tag: ClassTag[T]): Seq[T] = {
```
Comment (negokaz) [inline src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala:60]: [memo] This implementation simulates `receivePersisted(persistenceId: String, n: Int)` in akka-persistence-testkit

[akka/TestOps.scala at v2.6.17 · akka/akka](https://github.com/akka/akka/blob/v2.6.17/akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/TestOps.scala#L216-L220)

File: src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala [hunk 2]
```diff
@@ -28,4 +42,66 @@ final class RaftEventJournalTestKit(system: ActorSystem, settings: ClusterReplic
...
+    assert(result.sizeIs == n, s"Could read only ${result.size} events instead of expected $n")
+    assert(filtered.isEmpty, s"Persisted events [${filtered.mkString(", ")}] do not correspond to expected type")
+    setNextSeqNo(result.last)
+    result.map(_.event.asInstanceOf[T])
+  }
+
+  /**
+    * Check that nothing was persisted in the journal for particular persistence id.
+    */
+  def expectNothingPersisted(persistenceId: String): Unit = {
```
Comment (negokaz) [inline src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala:82]: [memo] [memo] This implementation simulates `expectNothingPersisted(persistenceId: String)` in akka-persistence-testkit

[akka/TestOps.scala at v2.6.17 · akka/akka](https://github.com/akka/akka/blob/v2.6.17/akka-persistence-testkit/src/main/scala/akka/persistence/testkit/scaladsl/TestOps.scala#L191-L195)

File: src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala [hunk 3]
```diff
@@ -301,15 +406,42 @@ private[entityreplication] class SnapshotSyncManager(
...
       }
-      .flatMapConcat { envelope =>
-        Source(envelope.event.entityIds)
+      .map { case (_, event, _) => event }
+      .fold(Option.empty[EntitySnapshotsUpdated]) {
+        // merge into single EntitySnapshotsUpdated
+        case (None, newEvent)        => Option(newEvent)
+        case (Some(event), newEvent) =>
+          // prefer the latest term, index and offset
+          Option(newEvent.mergeEntityIds(event))
```
Comment (xirc) [inline src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:440]: @negokaz 
I think there is no guarantee that the later incoming event has the latest term. For example, `akka-persistence-cassandra` maintains the order of the events per persistence ID per tag. [This document](https://doc.akka.io/docs/akka-persistence-cassandra/current/events-by-tag.html#:~:text=Order%20of%20the%20events%20is%20maintained%20per%20persistence%20id%20per%20tag%20by%20maintaining%20a%20sequence%20number%20for%20tagged%20events%20per%20persistence%20id.%20This%20is%20in%20addition%20to%20the%20normal%20sequence%20nr%20kept%20per%20persistence%20id.%20Events%20for%20the%20same%20persistence%20id%20will%20never%20be%20delivered%20out%20of%20order.) describes this consistency model.

I think we have to choose the latest term and index when merging `EntitySnapshotsUpdated` like the following:
```scala
  final case class EntitySnapshotsUpdated(
      snapshotLastLogTerm: Term,
      snapshotLastLogIndex: LogEntryIndex,
      entityIds: Set[NormalizedEntityId],
      offset: Offset,
  ) {
    def mergedWithNewOther(other: EntitySnapshotsUpdated): EntitySnapshotsUpdated = {
      val mergedEntityIds = this.entityIds ++ other.entityIds
      val (mergedTerm, mergedIndex) =
        if (this.snapshotLastLogTerm > other.snapshotLastLogTerm) {
          assert(this.snapshotLastLogIndex >= other.snapshotLastLogIndex, "TODO Is this true?")
          (this.snapshotLastLogTerm, this.snapshotLastLogIndex)
        } else if (this.snapshotLastLogTerm == other.snapshotLastLogTerm) {
          val greaterIndex = Ordering[LogEntryIndex].max(this.snapshotLastLogIndex, other.snapshotLastLogIndex)
          (this.snapshotLastLogTerm, greaterIndex)
        } else {
          assert(this.snapshotLastLogIndex <= other.snapshotLastLogIndex, "TODO Is this true?")
          (other.snapshotLastLogTerm, other.snapshotLastLogIndex)
        }
      val mergedOffset = other.offset // Offset is not ordered; choose other's offset that is supposed to new.
      EntitySnapshotsUpdated(mergedTerm, mergedIndex, mergedEntityIds, mergedOffset)
    }
  }
```

I'm not entirely sure that the assertions are correct in the above code. IMHO, the above assertions might always meet. I think this is because, in one specific Raft node, the log with the greater term has always a greater index than an index of another log with less term. What do you think about these concerns?

Comment (xirc) [reply src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:440]: I've realized `eventsByTag` might not maintain the order of events between different persistence ID now. Does this concerns affect the `SnapshotSyncManager` design?

File: src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala [hunk 4]
```diff
@@ -28,4 +42,66 @@ final class RaftEventJournalTestKit(system: ActorSystem, settings: ClusterReplic
...
+    assert(
+      persistedEvents.isEmpty,
+      s"Found persisted event [${persistedEvents.mkString(", ")}], but expected nothing instead",
+    )
+  }
+
+  /**
+    * Return the probe to verify tagged events with particular tag.
+    */
+  def verifyEventsByTag(tag: String): TestSubscriber.Probe[EventEnvelope] =
```
Comment (xirc) [inline src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala:101]: @negokaz 
I think this method could be renamed since this method does not verify any conditions.
I think the following names could also be possible:
* `createTestProbeOfEventsByTag`
* `probeOfEventsByTag`

What do you think about the name of this method?

**Review by xirc — COMMENTED** [review]
Great👍

I left some comments. I will review `SnapshotSyncManagerSpec` and `RaftEventJournalTestKitSpec` from now.

File: src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala (hunk 3 above)
Comment (negokaz) [reply src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:440]: @xirc Thank you for your important views.
As you said, we have to care that the order of the events is not guaranteed by `akka-persistence-cassandra` since `SnapshotSyncManager` detects that the process is completed with `snapshotLastLogIndex`.

https://github.com/lerna-stack/akka-entity-replication/blob/c1ed3d3b0f7d99c7cae45178925c57f258b3408c/src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala#L300-L317

We might be able to use `mergeSorted` to solve the problem.
Splitting the sources by `persistenceId` and using `mergeSorted` allow select the oldest event (with the lowest index) from each source.

[mergeSorted • Akka Documentation](https://doc.akka.io/docs/akka/2.6.17/stream/operators/Source-or-Flow/mergeSorted.html)

We have to also care that `SnapshotSyncManager`'s `persistenceId` contains `srcMemberIndex`.
More than one `SnapshotSyncManager` might have persisted events on the single node.

Do you have any opinions on this idea?

Comment (negokaz) [reply src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:440]: This idea may be difficult to implement.
We have to create the sources dynamically since the number of `persistenceId` is determined dynamically.

I think it might be rare that events are reordered since compaction and snapshot synchronization are not executed parallelly and the events are created by a single node.
How about dealing this the following?

- Verify that the order of `snapshotLastLogIndex`
- If it detects anomalies, aborts snapshot synchronization and logs error

Comment (negokaz) [reply src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:440]: Another idea:

- Remove `srcMemberIndex` from `SnapshotSyncManager`'s `persistenceId`
  - `SnapshotSyncManager` should maintain `Offset`s by `srcMemberIndex` with `Map`
  - This change breaks compatibility of persisted data
- Split sources by event types (`CompactionCompleted`, `SnapshotCopied`) and merge them with `mergeSorted`

This option can guarantee the order of events but breaks data compatibility.

Comment (xirc) [reply src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:440]: @negokaz

Thank you.
I also think this event reordering might seldom happen. I think your proposal is a suitable solution. I think we can handle this situation like:
* `SnapshotSyncManager` verifies that the current event `snapshotLastLogIndex` is greater than (or equal to) the immediately-previous `snapshotLastLogIndex`. If this condition is not satisfied, `SnapshotSyncManager` outputs an error log and replies with `SyncSnapshotFailed()` to `replyTo`.
  * `mergedWithNewOther` is not needed now. `mergeEntityIds` can be used.
* `SnapshotSyncManager` might have to verify `snapshotLastLogTerm` order?

Comment (negokaz) [reply src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:504]: @xirc I have implemented the verification.

244f3d3e

I guess it is usually impossible that index ordered correctly and term ordered reversed but I have dealt to make sure.

Comment (xirc) [reply src/main/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManager.scala:504]: @negokaz Thanks. Excellent!

File: src/test/scala/lerna/akka/entityreplication/util/EventStore.scala [hunk 5]
```diff
@@ -9,6 +9,8 @@ import lerna.akka.entityreplication.ClusterReplicationSettings
 object EventStore {
   def props(settings: ClusterReplicationSettings): Props = Props(new EventStore(settings))
   final case class PersistEvents(events: Seq[Any])
+
+  def persistenceId(): String = getClass.getCanonicalName
```
[the remark this answers is not in the document]
Comment (negokaz) [reply src/test/scala/lerna/akka/entityreplication/util/EventStore.scala]: @xirc 
Thanks!
I think it would be better to remove the `()`.

90c9627d

File: src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala [hunk 6]
```diff
@@ -28,4 +42,66 @@ final class RaftEventJournalTestKit(system: ActorSystem, settings: ClusterReplic
...
+    val query =
+      readJournal
+        .currentEventsByPersistenceId(
+          persistenceId,
+          fromSequenceNr = nextSeqNo(persistenceId),
+          toSequenceNr = Long.MaxValue,
+        )
+        .take(n)
+        .runWith(Sink.seq[EventEnvelope])
+    val result   = Await.result(query, remainingOrDefault)
```
[the remark this answers is not in the document]
Comment (negokaz) [reply src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala]: @xirc 

Thank you for your suggestion.
I guess it would be better to retry reading events.

ae3a93bc

File: src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala [hunk 7]
```diff
@@ -28,4 +42,66 @@ final class RaftEventJournalTestKit(system: ActorSystem, settings: ClusterReplic
...
+  def expectNothingPersisted(persistenceId: String): Unit = {
+    val query =
+      readJournal
+        .currentEventsByPersistenceId(
+          persistenceId,
+          fromSequenceNr = nextSeqNo(persistenceId),
+          toSequenceNr = Long.MaxValue,
+        )
+        .runWith(Sink.seq[EventEnvelope])
+    val persistedEvents = Await.result(query, remainingOrDefault).map(_.event)
```
[the remark this answers is not in the document]
Comment (negokaz) [reply src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala]: @xirc 

Thank you for your suggestion.
I think it would be better to change this method to ensure that there is no event during at-least `remainigOrDefault` timeout.

ae3a93bc

File: src/test/scala/lerna/akka/entityreplication/util/EventStore.scala (hunk 5 above)
[the remark this answers is not in the document]
Comment (xirc) [reply src/test/scala/lerna/akka/entityreplication/util/EventStore.scala]: @negokaz Thanks. Great!

File: src/test/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManagerSpec.scala [hunk 8]
```diff
@@ -66,106 +88,159 @@ class SnapshotSyncManagerSpec extends TestKit(ActorSystem()) with ActorSpec with
...
       srcRaftSnapshotStoreTestKit.saveSnapshots(srcSnapshots)
       val entityIds1 = srcSnapshots.filter(_.metadata.logEntryIndex == srcSnapshotLogIndex1).map(_.metadata.entityId)
       val entityIds2 = srcSnapshots.filter(_.metadata.logEntryIndex == srcSnapshotLogIndex2).map(_.metadata.entityId)
-      val entityIds  = entityIds1 ++ entityIds2
+      val entityIds3 = srcSnapshots.filter(_.metadata.logEntryIndex == srcSnapshotLogIndex3).map(_.metadata.entityId)
+      val entityIds  = entityIds1 ++ entityIds2 ++ entityIds3
       raftEventJournalTestKit.persistEvents(
         CompactionCompleted(srcMemberIndex, shardId, srcSnapshotTerm, srcSnapshotLogIndex1, entityIds1),
-        CompactionCompleted(srcMemberIndex, shardId, srcSnapshotTerm, srcSnapshotLogIndex2, entityIds2),
+        SnapshotCopied(nextOffset(), srcMemberIndex, shardId, srcSnapshotTerm, srcSnapshotLogIndex1, entityIds2),
```
[the remark this answers is not in the document]
Comment (negokaz) [reply src/test/scala/lerna/akka/entityreplication/raft/snapshot/sync/SnapshotSyncManagerSpec.scala]: @xirc 
Thanks!
I have fixed it. ce195f4f

File: src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala (hunk 7 above)
[the remark this answers is not in the document]
Comment (xirc) [reply src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala]: @negokaz Thanks. Great!

File: src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala (hunk 6 above)
[the remark this answers is not in the document]
Comment (xirc) [reply src/test/scala/lerna/akka/entityreplication/util/RaftEventJournalTestKit.scala]: @negokaz Thanks. Great!

**Review by xirc — APPROVED** [review]
Excellent! LGTM 👍

**Review by xirc — APPROVED** [review]
LGTM 👍
