### PR TITLE
Rollback preparation fails if required data have been deleted

### LINKED ISSUE #206: Rollback should fail without no deletion if required events or snapshots have already been deleted
For #201, #204

Once events or snapshots have been deleted, a rollback to a timestamp that requires such deleted events or snapshots is impossible. The rollback tool can't detect such deletions yet. If such a timestamp is specified, the rollback tool will delete all events and snapshots of the target Raft shard (or persistent actors of the target Raft shard will be inconsistent state).

The rollback tool can return a failure in rollback preparations (`RaftShardRollback.prepareRollback`) to address this issue. The tool first finds a sequence number for the rollback timestamp, and then it has a chance to verify the sequence number is valid for a rollback. In the verification, the tool should determine whether a persistent actor can roll back to the sequence number.

## Related code

* `RaftShardRollback.prepareRollback`: https://github.com/lerna-stack/akka-entity-replication/blob/v2.2.0/rollback-tool-cassandra/src/main/scala/lerna/akka/entityreplication/rollback/RaftShardRollback.scala#L29-L50
* `RaftShardRollback.prepareRaftActorsRollback`: https://github.com/lerna-stack/akka-entity-replication/blob/v2.2.0/rollback-tool-cassandra/src/main/scala/lerna/akka/entityreplication/rollback/RaftShardRollback.scala#L52-L75
* `RaftShardRollback.prepareSnapshotStoresRollback`: https://github.com/lerna-stack/akka-entity-replication/blob/v2.2.0/rollback-tool-cassandra/src/main/scala/lerna/akka/entityreplication/rollback/RaftShardRollback.scala#L77-L113
* `RaftShardRollback.prepareSnapshotSyncManagersRollback`: https://github.com/lerna-stack/akka-entity-replication/blob/v2.2.0/rollback-tool-cassandra/src/main/scala/lerna/akka/entityreplication/rollback/RaftShardRollback.scala#L115-L141
* `RaftShardRollback.prepareCommitLogStoreActorRollback`: https://github.com/lerna-stack/akka-entity-replication/blob/v2.2.0/rollback-tool-cassandra/src/main/scala/lerna/akka/entityreplication/rollback/RaftShardRollback.scala#L143-L187

### PR DESCRIPTION
**Pull request by xirc**
Closes #206 

Once data (events or snapshots) have been deleted, a rollback to a timestamp that requires such deleted data is impossible. This PR changes the rollback preparation (`prepareRollback`) such that it fails if required data have already been deleted.

The rollback preparation checks that each persistent actor can be rolled back (the persistent actor has a consistent state after rollback) based on sequence numbers. These checks involve the following component:
* `RollbackRequirementsVerifier`: for each persistent actor, it verifies whether the rollback is possible.
* `PersistentActorRollback.findRollbackRequirements`: for each persistent actor, it finds the possible lowest sequence number such that the persistent actor is consistent after rollbacks.
* `RollbackTimestampHintFinder`: it finds a timestamp hint if the rollback is impossible. Rollbacks should specify a newer timestamp than the hint, at least. While the hint might need to be more strictly correct, it helps to know why the given timestamp-based rollback is impossible.

### CODE REVIEW

File: rollback-tool-cassandra/src/test/scala/lerna/akka/entityreplication/rollback/RaftShardRollbackSpec.scala [hunk 1]
```diff
@@ -299,18 +546,95 @@ final class RaftShardRollbackSpec
...
+        .once()
+
+      // Test:
+      val exception = rollback.prepareSnapshotSyncManagersRollback(parameters).failed.futureValue
+      exception should be(a[RollbackRequirementsNotFulfilled])
+    }
+
   }
 
   "RaftShardRollback.prepareCommitLogStoreActorRollback" should {
```
Comment (negokaz) [inline rollback-tool-cassandra/src/test/scala/lerna/akka/entityreplication/rollback/RaftShardRollbackSpec.scala:634]: @xirc 

How about adding a test case for missing a rollback point (sequenceNr) for a leader RaftActor?
It will fulfill the following code coverage:

https://github.com/lerna-stack/akka-entity-replication/blob/82d69b48ef063516b9452f0cf1fa57c7c1ed65ee/rollback-tool-cassandra/src/main/scala/lerna/akka/entityreplication/rollback/RaftShardRollback.scala#L182-L183

**Review by negokaz — COMMENTED** [review]
@xirc 
Great! I left a comment.

File: rollback-tool-cassandra/src/test/scala/lerna/akka/entityreplication/rollback/RaftShardRollbackSpec.scala (hunk 1 above)
Comment (xirc) [reply rollback-tool-cassandra/src/test/scala/lerna/akka/entityreplication/rollback/RaftShardRollbackSpec.scala:634]: @negokaz 

Thanks! I've added a unit test for that case: d2877bd

**Review by negokaz — APPROVED** [review]
Awesome! LGTM 👍
